### ISSUE TITLE
Values for optin form DTM to Launch

### ISSUE THREAD

**Issue by koe-n** [Adobe-Marketing-Cloud/reactor-user-docs#15]
Hi,

On https://adobe.allegiancetech.com/cgi-bin/qwebcorporate.dll?69K2XN you explain where to get the information for DTM Company ID, but what value do you expect for the Company name? Is it the string in the top right corner? Or the xxx@AdobeOrg string?

Thanks,
Koen

**Comment by thebenrob** [comment]
We're not picky about that field.  String from the top right corner is best, but it's really just to make whitelisting a little simpler.

**Comment by koe-n** [comment]
Hello @thebenrob ,

I filled in the form last week (twice) but the feature was activated in the wrong DTM company (we have 2). Hence the question.

Can I contact anyone? We would like to start migration as soon as possible.

Thanks,
Koen

**Comment by thebenrob** [comment]
@koe-n, as long as you've filled it out at least once with the correct DTM Company ID, it'll get done with the next provisioning batch.
