### ISSUE TITLE
Async execution of Page Bottom, DOM Ready, Window Loaded

### ISSUE THREAD

**Issue by dwright-adobe** [Adobe-Marketing-Cloud/reactor-user-docs#36]
Hi,
For async deployments, can you please document (diagrams would help) the order in which Launch will fire rules triggered on the UI Events "Library Loaded", "Page Bottom", "DOM Ready", and "Window Loaded" when the Library Loaded event occurs before or after the underlying actual underlying events (or in the absence of _satellite.pageBottom()).

Example 1:
1. Async Launch library loads instantly (and underlying Library Loaded event is fired)
2. End of </body> is reached but there is no _satellite.pageBottom() event to fire
3. DOMContentLoaded() fires
4. window.load() fires
Expected order of rules: Library Loaded, Page Bottom, DOM Ready, Window Loaded

Example 2:
1. End of </body> is reached but there is no _satellite.pageBottom() event to fire
2. Async Launch library loads instantly (and underlying Library Loaded event is fired)
3. DOMContentLoaded() fires
4. window.load() fires
In what order do the rules fire?

Example 3:
1. End of </body> is reached but there is no _satellite.pageBottom() event to fire
2. DOMContentLoaded() fires
3. Async Launch library loads instantly (and underlying Library Loaded event is fired)
4. window.load() fires
In what order do the rules fire?

Example 4:
1. End of </body> is reached but there is no _satellite.pageBottom() event to fire
2. DOMContentLoaded() fires
3. window.load() fires
4. Async Launch library loads instantly (and underlying Library Loaded event is fired)
In what order do the rules fire? 
Is this scenario even possible? or is window.load() dependent on the Launch Library loading?

It seems like the order of the Library Load event in relation to the other page load events is unpredictable, but I hope the order of rule firing is and is the same as in Example 1. Regardless of how it works, i think this needs to be documented. One specific use case we are trying to decide is when should we fire our Analytics page view beacon if some of our data layer is not defined until the bottom of the page? Would the preferred event be Library Loaded, DOM Ready, or Window Loaded?

The information should go here:
https://docs.adobelaunch.com/client-side-information/asynchronous-deployment
@Aaronius

**Comment by Aaronius** [comment]
Hi @dwright-adobe. I plan on writing up something more formalized to go in the docs, but just to give you the answer beforehand: Every time the Launch library loads, no matter when or how it is loaded, all of the following events will trigger their respective rules in this order: Library Loaded, Page Bottom, DOM Ready, Window Loaded. If any phase has already occurred on the page, they'll fire their respective rules "immediately", while still respecting the order.

**Comment by Aaronius** [comment]
Also, in response to this:

> One specific use case we are trying to decide is when should we fire our Analytics page view beacon if some of our data layer is not defined until the bottom of the page? Would the preferred event be Library Loaded, DOM Ready, or Window Loaded?

I would use DOM Ready. DOM Ready will occur after the document has been loaded and parsed, which would be after "the bottom of the page". Library Loaded could be too early and Window Loaded is unnecessarily late.

**Comment by dwright-adobe** [comment]
Thanks! We decided on using DOM Ready for the [Tutorial](https://docs.adobe.com/content/help/en/experience-cloud/implementing-in-websites-with-launch/implement-solutions/analytics.html#send-the-page-view-beacon), but it's great to have this confirmation. I think it will be helpful to have the order stated in the documentation when you have time.

**Comment by Aaronius** [comment]
New documentation has been published here: https://docs.adobelaunch.com/launch-reference/client-side-information/asynchronous-deployment

Thanks for the request @dwright-adobe.
