### ISSUE TITLE
Broken link to docs on encypting keys

### ISSUE THREAD

**Issue by remear** [Adobe-Marketing-Cloud/reactor-user-docs#51]
Moved from Adobe-Marketing-Cloud/reactor-developer-docs/issues/1

Originally opened by @jkunz:

The link on https://docs.adobelaunch.com/launch-reference/publishing/adapters#sftp that points to instructions and Launch's public GPG keys points to https://developer.adobelaunch.com/guides/api/encrypting_values/ but should point to https://developer.adobelaunch.com/api/guides/encrypting_values/ .

**Comment by thebenrob** [comment]
Fixed the link
