### ISSUE TITLE
Missing AAM integration detailed info

### ISSUE THREAD

**Issue by jbaix** [Adobe-Marketing-Cloud/reactor-user-docs#9]
Hi!

In the page 'reactor-user-docs/extension-reference/adobe-analytics-extension.md', I cannot find information regarding the Adobe Audience Manager section:

![image](https://user-images.githubusercontent.com/14937333/41221898-cd662a80-6d65-11e8-8b48-9a5c88cdd3be.png)

**Comment by thebenrob** [comment]
@srhoades-adobe can you take this one?  Let's provide a little more info in the docs about where to get these settings from.

**Comment by thebenrob** [comment]
This has been updated: https://docs.adobelaunch.com/extension-reference/adobe-extensions/adobe-analytics-extension#adobe-audience-manager
